#WARNING: DO NOT USE TAB FOR IDENT YAML FILE: This is not permitted by the YAML spec
## urdf and srdf filename
ros_end_effector:
  urdf_path: "urdf/heri_II.urdf"
  srdf_path: "srdf/heri_II.srdf"
  
  
## Arguments for rosee_plugin control for gazebo. Similar syntax to
# the one used by "official" ros plugin http://gazebosim.org/tutorials/?tut=ros_control
rosee_gazebo_plugins_args: #robot name
  #Controller for each joint. type now is only JointPositionControllerfor JointVelocityController
  motor_finger1_position_controller:
    type: JointPositionController
    joint_name: motor_finger1
    pid: {p: 0.3, i: 0.001, d: 0.00005}

  motor_finger2_position_controller:
    type: JointPositionController
    joint_name: motor_finger2
    pid: {p: 0.3, i: 0.001, d: 0.00005}

  motor_finger3_position_controller:
    type: JointPositionController
    joint_name: motor_finger3
    pid: {p: 0.3, i: 0.001, d: 0.00005}
    
  motor_thumb_position_controller:
    type: JointPositionController
    joint_name: motor_thumb
    pid: {p: 0.3, i: 0.001, d: 0.00005}
          
################## Specific info for rosee planner ############################
hand_info:
  #The order here will be the order followed by the other info
  fingers_names: [finger_1, finger_2, finger_3, thumb]
  motors_names: [motor_finger1, motor_finger2, motor_finger3, motor_thumb]
  #
  #K_t : 0.0418 # Torque coefficent of the motor [Nm/A]
  #R_M : 2.62 # Eletrical terminal resistance of the motor [ohm]
  #K_p : 1? p gain of pid. It is hardcoded in the heri firmware
  #Gratio = 138
  #Ee = 0.9; Efficient of gearhead, The 0.9 is the maximum efficiency of the motor.
  #stiffness = Gratio * Ee * K_t * K_p / R_M = 138 * 0.9 * 0.0418 * 1 / 2.62 = 1.981511450381679389315
  motors_stiffness: [1.9815114503816793893155, 1.981511450381679389315, 1.981511450381679389315, 1.981511450381679389315] 
  tips_frictions: [0.5, 0.5, 0.5, 0.5] #(Rubber against stainless steel 316)https://www.engineersedge.com/coeffients_of_friction.htm
  # I know these below can be in the urdf... but EEHal for now does not have access to urdf
  motors_torque_limits: [3.3, 3.3, 3.3, 3.3] #Newton/meter, continuos torque, but peaks for short time can reach 5.3 N/m intermittent torque
  # tip frame position respect to last joint position, x and y coordinates (again present in the urdf)
  tip_joint_to_tip_frame_x: [0.0175, 0.0175, 0.0175, 0.0175]
  tip_joint_to_tip_frame_y: [-0.0111, -0.0111, -0.0111, -0.0111]

##############
### real hand
##############

ec_board_ctrl :
  #eth_iface: rteth0
  eth_iface: enp3s0
  #sync_cycle_time_ns: 500000
  #sync_cycle_time_ns: 1000000
  #sync_cycle_time_ns: 2000000
  #sync_cycle_time_ns: 5000000
  #sync_cycle_time_ns: 10000000
  #sync_cycle_time_ns: 100000000
  sync_cycle_time_ns: 0
  sync_cycle_offset_ns: 1000000000
  sync_point_ns : 500000
  power_off_boards: false
  reset_micro : true
  
ec_boards_base :
  app_mode : run_mode
  #app_mode : config_mode
  robot_name : NoNe
  read_SDOs : false
  use_pipes : true
  log_level : 1
  #fault_power_off : true
  # only for TestESC
  #use_ecat_pos_as_id : true

LpESC_X:
  sign: 1
  pos_offset: 0
  control_mode : 3B_motor_pos_ctrl
  pid :
    position: [100000.0 , 0.0 , 1.0]

LpHandESC_X:
  sign: 1
  pos_offset: 0
  control_mode : 3B_motor_pos_ctrl
  pid :
    position: [100000.0 , 0.0 , 1.0]

HeriHandESC_X:
  sign: 1
  pos_offset: 0
  control_mode : 3B_motor_pos_ctrl
  pid :
    position: [100000.0 , 0.0 , 1.0]
